export default {
  colors: {
    primary: '#F1F5F8',
    onPrimary: '#161A4B',
    primaryContainer: '#E3E8EB',
    onPrimaryContainer: '#818193',
    secondary: '#818193',
    onSecondary: '#FFFFFF',
    secondaryContainer: '#E3E8EB',
    onSecondaryContainer: '#161A4B',
    tertiary: '#DFF5F4',
    onTertiary: '#161A4B',
    tertiaryContainer: '#',
    onTertiaryContainer: '#',
    error: '#DB3526',
    onError: '#',
    errorContainer: '#',
    onErrorContainer: '#',
    background: '#F1F5F8',
    onBackground: '#161A4B',
    surface: '#FFFFFF',
    onSurface: '#191C1D',
    surfaceVariant: '#',
    onSurfaceVariant: '#4A4A68',
    outline: '#BBBBCA',
    outlineVariant: '#000000',
    inverseSurface: '#',
    inverseOnSurface: '#',
    inversePrimary: '#',
    elevation: {
      level0: 'transparent',
      level1: '#',
      level2: '#',
      level3: '#',
      level4: '#',
      level5: '#',
    },
    surfaceDisabled: '#',
    onSurfaceDisabled: '#',
  },
  fonts: {
    regular: {
      fontFamily: 'Roboto-Regular',
      fontWeight: '400',
    },
    medium: {
      fontFamily: 'Roboto-Medium',
      fontWeight: '500',
    },
    light: {
      fontFamily: 'Roboto-Light',
      fontWeight: '300',
    },
    thin: {
      fontFamily: 'Roboto-Thin',
      fontWeight: '100',
    },
  },
};
